### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by maphilli14** [rankinstudio/unWrap#2]
how do i get unWrap installed? I cloned it but I assume it needs to be put into the other lib/script folders? like pip...

**Comment by rankinstudio** [comment]
It is a script meant to have a wide range of use cases, so it will require some python knowledge to use it. The test.py gives an example of how you can use the script. You can call the script any way you'd like. Manually, or from a cron job.

**Comment by maphilli14** [comment]
ImportError: cannot import name 'unwrap' from 'unWrap' (unknown location)

**Comment by maphilli14** [comment]
cd into clone and then ran python interactively, np
